#include <iostream>
#include <string>
#include <vector>
#include <algorithm>
#include <filesystem>
#include <limits>
#include <sstream>
#include <fstream>
#include <functional>
#include <future>
#define NOMINMAX
#include <windows.h>
#include <shellapi.h>

namespace fs = std::filesystem;

// ANSI color codes (requires Windows 10+)
#define COL_RESET   "\033[0m"
#define COL_BOLD    "\033[1m"
#define COL_GREY    "\033[90m"
#define COL_RED     "\033[91m"
#define COL_GREEN   "\033[92m"
#define COL_YELLOW  "\033[93m"
#define COL_CYAN    "\033[96m"
#define COL_WHITE   "\033[97m"

// Subdirectories that must never be deleted — losing these causes full project rebuild
const std::vector<std::string> PROTECTED_DIRS = {
    "BuildRules",    // compiled C# module rules — deleting forces a full module-rules recompile
    "UBTCache",      // UBT dependency cache
    "ProjectFiles",  // VS project files (regenerated by UnrealVersionSelector)
    "Inc",           // UHT-generated headers — deleting triggers UHT rerun + downstream recompile cascade
};

// Files inside Intermediate that must never be deleted — covers ALL modules in the build target
const std::vector<std::string> PROTECTED_FILES = {
    "ActionHistory.bin",  // UBT action graph cache — if deleted, UBT rebuilds every module from scratch
    "SourceFileCache.bin",// UBT source-file scan cache — if deleted, UBT re-scans every header in the project
    "XmlConfigCache.bin", // UBT XML-config cache — if deleted, UBT re-parses all engine XML configs
};

// File extensions inside Intermediate that must never be deleted
// Deleting these causes UHT to re-run for the affected target, which re-generates headers
// and can trigger a cascade recompile of every module that includes them.
const std::vector<std::string> PROTECTED_EXTENSIONS = {
    ".uhtmanifest",  // UHT input manifest — lists every header UHT must process for a target
    ".uhtsettings",  // UHT configuration per target
    ".uhtpath",      // UHT path descriptor per target
};

// One entry per project/plugin — groups Binaries + Intermediate together
struct GroupInfo
{
    std::string name;             // project name or plugin name
    fs::path    binariesPath;     // empty if not present
    fs::path    intermediatePath; // empty if not present
    int         binariesCount    = 0;
    int         intermediateCount = 0;
    bool        selected         = false;

    int totalCount() const { return binariesCount + intermediateCount; }
};

// ----------------------------------------------------------------
// Helpers
// ----------------------------------------------------------------

void EnableAnsiColors()
{
    HANDLE hOut = GetStdHandle(STD_OUTPUT_HANDLE);
    DWORD mode  = 0;
    GetConsoleMode(hOut, &mode);
    SetConsoleMode(hOut, mode | ENABLE_VIRTUAL_TERMINAL_PROCESSING);
}

fs::path GetExeDir()
{
    wchar_t buffer[MAX_PATH];
    GetModuleFileNameW(nullptr, buffer, MAX_PATH);
    return fs::path(buffer).parent_path();
}

// Counts only files that would actually be deleted — mirrors deletion logic
// isBinaries=true  → only .dll / .pdb  (skip .modules and protected dirs)
// isBinaries=false → all files         (skip protected dirs)
// skipDirs: additional directory names to skip (on top of PROTECTED_DIRS)
int CountDeletableFiles(const std::wstring& dir, bool isBinaries,
                        const std::vector<std::string>& skipDirs = {})
{
    // Skip if the folder name itself is protected or in skipDirs
    fs::path dirPath(dir);
    std::string folderName = dirPath.filename().string();
    for (const auto& item : PROTECTED_DIRS)
        if (_stricmp(folderName.c_str(), item.c_str()) == 0) return 0;
    for (const auto& item : skipDirs)
        if (_stricmp(folderName.c_str(), item.c_str()) == 0) return 0;

    int count = 0;
    std::wstring search = dir + L"\\*";

    WIN32_FIND_DATAW fd;
    HANDLE hFind = FindFirstFileExW(
        search.c_str(), FindExInfoBasic, &fd,
        FindExSearchNameMatch, nullptr, FIND_FIRST_EX_LARGE_FETCH
    );
    if (hFind == INVALID_HANDLE_VALUE) return 0;

    std::vector<std::wstring> subdirs;
    do
    {
        if (fd.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY)
        {
            if (fd.cFileName[0] != L'.')
                subdirs.push_back(dir + L"\\" + fd.cFileName);
        }
        else
        {
            if (isBinaries)
            {
                // Only count .dll and .pdb, skip .modules
                std::wstring fname = fd.cFileName;
                auto dot = fname.rfind(L'.');
                if (dot != std::wstring::npos)
                {
                    std::wstring ext = fname.substr(dot);
                    std::transform(ext.begin(), ext.end(), ext.begin(), ::towlower);
                    if (ext == L".dll" || ext == L".pdb") ++count;
                }
            }
            else
            {
                // Skip files with protected extensions (.uhtmanifest etc.) — deleting them causes UHT reruns
                std::wstring fname = fd.cFileName;
                auto dot = fname.rfind(L'.');
                bool protectedExt = false;
                if (dot != std::wstring::npos)
                {
                    std::wstring wext = fname.substr(dot);
                    std::transform(wext.begin(), wext.end(), wext.begin(), ::towlower);
                    for (const auto& pe : PROTECTED_EXTENSIONS)
                    {
                        std::wstring wpe(pe.begin(), pe.end()); // safe: extensions are ASCII
                        if (wext == wpe) { protectedExt = true; break; }
                    }
                }
                // Skip globally protected files (ActionHistory.bin, SourceFileCache.bin, etc.)
                if (!protectedExt)
                {
                    for (const auto& pf : PROTECTED_FILES)
                    {
                        std::wstring wpf(pf.begin(), pf.end()); // safe: filenames are ASCII
                        if (_wcsicmp(fname.c_str(), wpf.c_str()) == 0) { protectedExt = true; break; }
                    }
                }
                if (!protectedExt) ++count;
            }
        }
    } while (FindNextFileW(hFind, &fd));
    FindClose(hFind);

    for (const auto& sub : subdirs)
        count += CountDeletableFiles(sub, isBinaries, skipDirs);
    return count;
}

bool ContainsIgnoreCase(const std::string& haystack, const std::string& needle)
{
    return std::search(
        haystack.begin(), haystack.end(),
        needle.begin(),   needle.end(),
        [](char a, char b) { return std::tolower((unsigned char)a) == std::tolower((unsigned char)b); }
    ) != haystack.end();
}

bool IsProtected(const fs::path& path)
{
    std::string name = path.filename().string();
    for (const auto& item : PROTECTED_DIRS)
        if (_stricmp(name.c_str(), item.c_str()) == 0)
            return true;
    return false;
}

// Returns the first *.uproject found directly inside startPath, or an empty path if none exists
fs::path FindUprojectFile(const fs::path& startPath)
{
    try
    {
        for (auto& e : fs::directory_iterator(startPath, fs::directory_options::skip_permission_denied))
            if (e.is_regular_file() && e.path().extension() == ".uproject")
                return e.path();
    }
    catch (...) {}
    return {};
}

std::string GetProjectName(const fs::path& startPath)
{
    fs::path uproject = FindUprojectFile(startPath);
    if (!uproject.empty()) return uproject.stem().string();
    return startPath.filename().string();
}

// forward declaration (defined in Clean section below)
void CleanPath(const fs::path& root,
               const std::vector<std::string>& skipDirNames   = {},
               const std::vector<std::string>& skipContaining = {});

// ----------------------------------------------------------------
// Scan
// ----------------------------------------------------------------

// Returns module names found directly inside <projectRoot>/Source/ — each subdirectory that
// contains a *.Build.cs file is a module.  This is used to identify which x64/ subdirectories
// belong to the project (vs engine or plugin modules that share the same x64/ folder).
std::vector<std::string> GetProjectModuleNames(const fs::path& projectRoot)
{
    std::vector<std::string> modules;
    fs::path sourceDir = projectRoot / "Source";
    if (!fs::exists(sourceDir)) return modules;
    try
    {
        for (auto& entry : fs::directory_iterator(sourceDir, fs::directory_options::skip_permission_denied))
        {
            if (!entry.is_directory()) continue;
            // A directory is a module if it contains a <Name>.Build.cs file
            for (auto& f : fs::directory_iterator(entry.path(), fs::directory_options::skip_permission_denied))
            {
                if (!f.is_regular_file()) continue;
                // Extension must be ".cs" and the stem must end in ".Build"
                std::string ext  = f.path().extension().string();
                std::string stem = f.path().stem().string();           // e.g. "Calypso.Build"
                std::string stemExt = fs::path(stem).extension().string(); // ".Build"
                if (_stricmp(ext.c_str(), ".cs") == 0 &&
                    _stricmp(stemExt.c_str(), ".Build") == 0)
                { modules.push_back(entry.path().filename().string()); break; }
            }
        }
    }
    catch (...) {}
    return modules;
}

// Clean only the project module dirs inside x64/<Target>/<Config>/<ModuleName>/.
// This deletes the project module's .obj files without touching SharedPCH dirs
// (Core, Engine, etc.) that are also stored under x64/.
void CleanProjectModuleDirsUnderX64(const fs::path& x64Base,
                                     const std::vector<std::string>& moduleNames)
{
    if (!fs::exists(x64Base) || moduleNames.empty()) return;
    try
    {
        for (auto& targetEntry : fs::directory_iterator(x64Base, fs::directory_options::skip_permission_denied))
        {
            if (!targetEntry.is_directory()) continue;
            for (auto& configEntry : fs::directory_iterator(targetEntry.path(), fs::directory_options::skip_permission_denied))
            {
                if (!configEntry.is_directory()) continue;
                for (const auto& mod : moduleNames)
                    CleanPath(configEntry.path() / mod);
            }
        }
    }
    catch (...) {}
}

// Count deletable files inside the project module dirs under x64/ (mirrors CleanProjectModuleDirsUnderX64).
int CountProjectModuleFilesUnderX64(const fs::path& x64Base,
                                     const std::vector<std::string>& moduleNames)
{
    int total = 0;
    if (!fs::exists(x64Base) || moduleNames.empty()) return total;
    try
    {
        for (auto& targetEntry : fs::directory_iterator(x64Base, fs::directory_options::skip_permission_denied))
        {
            if (!targetEntry.is_directory()) continue;
            for (auto& configEntry : fs::directory_iterator(targetEntry.path(), fs::directory_options::skip_permission_denied))
            {
                if (!configEntry.is_directory()) continue;
                for (const auto& mod : moduleNames)
                {
                    fs::path modDir = configEntry.path() / mod;
                    if (fs::exists(modDir))
                        total += CountDeletableFiles(modDir.wstring(), false);
                }
            }
        }
    }
    catch (...) {}
    return total;
}

// Build a GroupInfo for a given owner directory (project root or plugin dir).
// isProjectRoot=true  → skips "x64/" when counting Intermediate files (matches CleanSelected logic)
GroupInfo BuildGroup(const std::string& name, const fs::path& ownerDir, bool isProjectRoot = false)
{
    GroupInfo g;
    g.name = name;

    fs::path bin = ownerDir / "Binaries";
    fs::path mid = ownerDir / "Intermediate";

    if (fs::exists(bin) && fs::is_directory(bin))   g.binariesPath     = bin;
    if (fs::exists(mid) && fs::is_directory(mid))   g.intermediatePath = mid;

    // For the project root:
    //   - x64/ is skipped in the main Intermediate count because it contains SharedPCH files
    //     used by ALL modules (engine, plugins).  Deleting them causes full rebuild.
    //   - We separately count only the project module dirs under x64/ (those will be cleaned).
    std::vector<std::string> intermediateSkip;
    if (isProjectRoot) intermediateSkip.push_back("x64");

    // Count only deletable files, in parallel
    std::future<int> fb, fm;
    if (!g.binariesPath.empty())
        fb = std::async(std::launch::async, CountDeletableFiles,
                        g.binariesPath.wstring(), true, std::vector<std::string>{});
    if (!g.intermediatePath.empty())
        fm = std::async(std::launch::async, CountDeletableFiles,
                        g.intermediatePath.wstring(), false, intermediateSkip);

    if (!g.binariesPath.empty())     g.binariesCount     = fb.get();
    if (!g.intermediatePath.empty()) g.intermediateCount = fm.get();

    // Project root: add count for project module obj files under x64/
    if (isProjectRoot && !g.intermediatePath.empty())
    {
        auto moduleNames = GetProjectModuleNames(ownerDir);
        fs::path x64Base = g.intermediatePath / "Build" / "Win64" / "x64";
        g.intermediateCount += CountProjectModuleFilesUnderX64(x64Base, moduleNames);
    }

    return g;
}

// Recursively find all directories under pluginsDir that have
// a direct Binaries or Intermediate child (these are plugin owners)
std::vector<fs::path> FindPluginOwners(const fs::path& pluginsDir)
{
    std::vector<fs::path> owners;
    if (!fs::exists(pluginsDir)) return owners;
    try
    {
        auto it = fs::recursive_directory_iterator(pluginsDir, fs::directory_options::skip_permission_denied);
        for (auto& e : it)
        {
            if (!e.is_directory()) continue;
            std::string name = e.path().filename().string();
            if (_stricmp(name.c_str(), "Binaries") == 0 ||
                _stricmp(name.c_str(), "Intermediate") == 0)
            {
                owners.push_back(e.path().parent_path());
                it.disable_recursion_pending();
            }
        }
    }
    catch (...) {}

    // Remove duplicates (a dir can have both Binaries and Intermediate)
    std::sort(owners.begin(), owners.end());
    owners.erase(std::unique(owners.begin(), owners.end()), owners.end());
    return owners;
}

std::vector<GroupInfo> FindTargetFolders(const fs::path& startPath)
{
    std::vector<GroupInfo> result;

    // 1. Project root (isProjectRoot=true so the count mirrors what CleanSelected will actually delete)
    std::string projectName = GetProjectName(startPath);
    auto rootGroup = BuildGroup(projectName, startPath, /*isProjectRoot=*/true);
    if (!rootGroup.binariesPath.empty() || !rootGroup.intermediatePath.empty())
        result.push_back(std::move(rootGroup));

    // 2. All plugin owners (handles nested plugin structures)
    auto pluginOwners = FindPluginOwners(startPath / "Plugins");

    std::vector<std::future<GroupInfo>> futures;
    futures.reserve(pluginOwners.size());
    for (auto& dir : pluginOwners)
        futures.push_back(std::async(std::launch::async, BuildGroup,
                                     dir.filename().string(), dir, /*isProjectRoot=*/false));

    for (auto& f : futures)
    {
        auto g = f.get();
        if (!g.binariesPath.empty() || !g.intermediatePath.empty())
            result.push_back(std::move(g));
    }

    return result;
}

// ----------------------------------------------------------------
// Clean
// ----------------------------------------------------------------

// Prefix \\?\ to support paths longer than MAX_PATH (260 chars)
std::wstring LongPath(const fs::path& p)
{
    std::wstring w = p.wstring();
    if (w.size() >= 4 && w.substr(0, 4) == L"\\\\?\\") return w;
    if (w.size() >= 2 && w[0] == L'\\' && w[1] == L'\\')
        return L"\\\\?\\UNC\\" + w.substr(2);
    return L"\\\\?\\" + w;
}

void ForceDeleteFile(const fs::path& filePath)
{
    std::wstring lp = LongPath(filePath);
    // Clear read-only attribute if set
    DWORD attrs = GetFileAttributesW(lp.c_str());
    if (attrs != INVALID_FILE_ATTRIBUTES && (attrs & FILE_ATTRIBUTE_READONLY))
        SetFileAttributesW(lp.c_str(), attrs & ~FILE_ATTRIBUTE_READONLY);
    DeleteFileW(lp.c_str());
}

// skipContaining: for Binaries, skip DLL/PDB files whose stem contains any of these strings.
// Used to protect plugin DLLs that live in the project's Binaries directory.
void DeleteFilesInDir(const fs::path& dir, const std::vector<std::string>& skipContaining = {})
{
    if (!fs::exists(dir)) return;
    bool isBinaries = ContainsIgnoreCase(dir.string(), "Binaries");

    // Collect first, then delete — modifying dir while iterating causes skipped entries
    std::vector<fs::path> toDelete;
    try
    {
        for (auto& e : fs::directory_iterator(dir, fs::directory_options::skip_permission_denied))
        {
            if (!e.is_regular_file()) continue;
            std::string ext = e.path().extension().string();
            std::transform(ext.begin(), ext.end(), ext.begin(),
                           [](unsigned char c) { return (char)std::tolower(c); });
            if (isBinaries)
            {
                if (ext == ".modules") continue;
                if (ext != ".dll" && ext != ".pdb") continue;
                // Skip DLL/PDB files that belong to a plugin (stem contains plugin name)
                if (!skipContaining.empty())
                {
                    std::string stem = e.path().stem().string();
                    bool skip = false;
                    for (const auto& s : skipContaining)
                        if (ContainsIgnoreCase(stem, s)) { skip = true; break; }
                    if (skip) continue;
                }
                toDelete.push_back(e.path());
            }
            else {
                // Skip globally protected files (e.g. UBT action cache)
                std::string fname = e.path().filename().string();
                bool protectedFile = false;
                for (const auto& pf : PROTECTED_FILES)
                    if (_stricmp(fname.c_str(), pf.c_str()) == 0) { protectedFile = true; break; }
                if (protectedFile) continue;
                // Skip files with protected extensions (e.g. UHT manifests)
                std::string ext = e.path().extension().string();
                std::transform(ext.begin(), ext.end(), ext.begin(),
                               [](unsigned char c){ return (char)std::tolower(c); });
                for (const auto& pe : PROTECTED_EXTENSIONS)
                    if (ext == pe) { protectedFile = true; break; }
                if (!protectedFile) toDelete.push_back(e.path());
            }
        }
    }
    catch (...) {}

    for (auto& p : toDelete)
        ForceDeleteFile(p);
}

// skipDirNames:    skip (and don't recurse into) subdirectories with these names
// skipContaining:  when inside a Binaries dir, skip DLL/PDB files whose stem contains these strings
void CleanPath(const fs::path& root,
               const std::vector<std::string>& skipDirNames,
               const std::vector<std::string>& skipContaining)
{
    if (root.empty() || !fs::exists(root)) return;
    try
    {
        auto it = fs::recursive_directory_iterator(root, fs::directory_options::skip_permission_denied);
        for (auto& e : it)
        {
            if (!e.is_directory()) continue;
            std::string name = e.path().filename().string();
            bool skip = IsProtected(e.path());
            if (!skip)
                for (const auto& s : skipDirNames)
                    if (_stricmp(name.c_str(), s.c_str()) == 0) { skip = true; break; }
            if (skip) { it.disable_recursion_pending(); continue; }
            DeleteFilesInDir(e.path(), skipContaining);
        }
        if (!IsProtected(root)) DeleteFilesInDir(root, skipContaining);
    }
    catch (...) {}
}

void DeleteSlnFiles(const fs::path& startPath)
{
    try
    {
        for (auto& e : fs::directory_iterator(startPath, fs::directory_options::skip_permission_denied))
            if (e.is_regular_file() && e.path().extension() == ".sln")
            { std::error_code ec; fs::remove(e.path(), ec); }
    }
    catch (...) {}
}

void GenerateProjectFiles(const fs::path& uprojectPath)
{
    fs::path selectorPath =
        L"C:\\Program Files (x86)\\Epic Games\\Launcher\\Engine\\Binaries\\Win64\\UnrealVersionSelector.exe";
    if (!fs::exists(selectorPath))
    {
        std::cout << COL_RED << "  [!] UnrealVersionSelector.exe not found." << COL_RESET << "\n";
        return;
    }
    std::wstring selectorW = selectorPath.wstring();
    std::wstring args = L"/projectfiles \"" + uprojectPath.wstring() + L"\"";
    SHELLEXECUTEINFOW sei = {};
    sei.cbSize = sizeof(sei); sei.fMask = SEE_MASK_NOCLOSEPROCESS;
    sei.lpFile = selectorW.c_str(); sei.lpParameters = args.c_str(); sei.nShow = SW_HIDE;
    if (ShellExecuteExW(&sei))
    {
        std::cout << COL_YELLOW << "  Generating project files..." << COL_RESET;
        WaitForSingleObject(sei.hProcess, INFINITE);
        CloseHandle(sei.hProcess);
        std::cout << COL_GREEN << " Done." << COL_RESET << "\n";
    }
    else std::cout << COL_RED << "  [!] Failed to generate project files." << COL_RESET << "\n";
}

void OpenUproject(const fs::path& uprojectPath)
{
    ShellExecuteW(nullptr, L"open", uprojectPath.wstring().c_str(), nullptr, nullptr, SW_SHOWNORMAL);
}

void CleanSelected(std::vector<GroupInfo>& groups, const fs::path& startPath)
{
    // Plugin group names — used to protect their subdirs inside the project root Intermediate
    std::vector<std::string> pluginNames;
    for (size_t i = 1; i < groups.size(); ++i)
        pluginNames.push_back(groups[i].name);

    std::cout << "\n" << COL_YELLOW << "Cleaning..." << COL_RESET << "\n";
    int cleaned = 0;
    for (size_t i = 0; i < groups.size(); ++i)
    {
        auto& g = groups[i];
        if (!g.selected) continue;
        if (i == 0)
        {
            // Project root: protect plugin and shared-build artefacts so UBT doesn't rebuild them.
            //
            // x64/ layout inside Intermediate/Build/Win64/x64/:
            //   <Target>/<Config>/Core/    ← SharedPCH for engine modules  → KEEP
            //   <Target>/<Config>/Engine/  ← SharedPCH for engine modules  → KEEP
            //   <Target>/<Config>/<Plugin>/← plugin SharedPCH              → KEEP
            //   <Target>/<Config>/<Mod>/   ← project module .obj files     → DELETE
            //
            // Strategy: skip x64/ in the main CleanPath (preserves all SharedPCH), then
            // specifically delete only the project module subdirs under x64/.
            std::vector<std::string> projectSkipDirs = pluginNames;
            projectSkipDirs.push_back("x64");
            CleanPath(g.binariesPath,     pluginNames, pluginNames);
            CleanPath(g.intermediatePath, projectSkipDirs);

            // Delete project module .obj files under x64/ without touching SharedPCH dirs
            auto moduleNames = GetProjectModuleNames(startPath);
            fs::path x64Base = g.intermediatePath / "Build" / "Win64" / "x64";
            CleanProjectModuleDirsUnderX64(x64Base, moduleNames);
        }
        else
        {
            CleanPath(g.binariesPath);
            CleanPath(g.intermediatePath);
        }
        ++cleaned;
    }
    DeleteSlnFiles(startPath);
    std::cout << COL_GREEN << "  " << cleaned << " entry(s) cleaned." << COL_RESET << "\n";
}

void RunGenerateProjectFiles(const fs::path& startPath)
{
    fs::path uproject = FindUprojectFile(startPath);
    if (!uproject.empty()) GenerateProjectFiles(uproject);
}

// ----------------------------------------------------------------
// Engine discovery
// ----------------------------------------------------------------

// Relative path of the engine's UnrealBuildTool launcher, used to validate an engine root
const wchar_t* ENGINE_BUILD_BAT = L"Engine\\Build\\BatchFiles\\Build.bat";

bool IsValidEngineRoot(const fs::path& root)
{
    if (root.empty()) return false;
    std::error_code ec;
    return fs::exists(root / ENGINE_BUILD_BAT, ec);
}

// Reads the "EngineAssociation" value out of a .uproject.
// The file is JSON but we only need one key, so a plain text scan avoids a JSON dependency.
// Returns e.g. "5.8" for a launcher install, or a GUID for a source build.
std::string ReadEngineAssociation(const fs::path& uproject)
{
    std::ifstream in(uproject);
    if (!in) return {};
    std::string text((std::istreambuf_iterator<char>(in)), std::istreambuf_iterator<char>());

    const std::string key = "\"EngineAssociation\"";
    size_t pos = text.find(key);
    if (pos == std::string::npos) return {};
    pos = text.find(':', pos + key.size());
    if (pos == std::string::npos) return {};
    size_t open = text.find('"', pos);
    if (open == std::string::npos) return {};
    size_t close = text.find('"', open + 1);
    if (close == std::string::npos) return {};
    return text.substr(open + 1, close - open - 1);
}

// Reads a REG_SZ value; returns an empty string when the key or value is missing
std::wstring ReadRegistryString(HKEY hive, const std::wstring& subKey, const std::wstring& valueName)
{
    wchar_t buffer[MAX_PATH * 2];
    DWORD size = sizeof(buffer);
    DWORD flags = RRF_RT_REG_SZ;
    if (RegGetValueW(hive, subKey.c_str(), valueName.c_str(), flags, nullptr, buffer, &size) != ERROR_SUCCESS)
        return {};
    return std::wstring(buffer);
}

// Environment variable name matching QuickBuild.bat's convention: "5.8" -> UE_5_8_PATH
std::wstring EngineEnvVarName(const std::string& assoc)
{
    std::wstring name = L"UE_";
    for (char c : assoc)
        name += (c == '.') ? L'_' : (wchar_t)c;
    name += L"_PATH";
    return name;
}

std::wstring ReadEnvVar(const std::wstring& name)
{
    DWORD needed = GetEnvironmentVariableW(name.c_str(), nullptr, 0);
    if (needed == 0) return {};
    std::wstring value(needed, L'\0');
    DWORD written = GetEnvironmentVariableW(name.c_str(), value.data(), needed);
    value.resize(written);
    return value;
}

// Persists an environment variable for the current user (the API equivalent of setx)
// and makes it visible to this process immediately.
void PersistUserEnvVar(const std::wstring& name, const std::wstring& value)
{
    SetEnvironmentVariableW(name.c_str(), value.c_str());

    HKEY hKey = nullptr;
    if (RegOpenKeyExW(HKEY_CURRENT_USER, L"Environment", 0, KEY_SET_VALUE, &hKey) != ERROR_SUCCESS)
        return;
    RegSetValueExW(hKey, name.c_str(), 0, REG_SZ,
                   reinterpret_cast<const BYTE*>(value.c_str()),
                   (DWORD)((value.size() + 1) * sizeof(wchar_t)));
    RegCloseKey(hKey);

    // Notify running shells so new processes pick the variable up without a logoff
    DWORD_PTR result = 0;
    SendMessageTimeoutW(HWND_BROADCAST, WM_SETTINGCHANGE, 0,
                        reinterpret_cast<LPARAM>(L"Environment"),
                        SMTO_ABORTIFHUNG, 5000, &result);
}

// Resolves the engine root for a given EngineAssociation value, without prompting.
// Order: env var -> launcher registry -> source-build registry -> default install path.
fs::path ResolveEngineRoot(const std::string& assoc)
{
    if (assoc.empty()) return {};

    // 1. Environment variable (shared with QuickBuild.bat)
    fs::path fromEnv = ReadEnvVar(EngineEnvVarName(assoc));
    if (IsValidEngineRoot(fromEnv)) return fromEnv;

    std::wstring wassoc(assoc.begin(), assoc.end()); // safe: version strings / GUIDs are ASCII

    // 2. Launcher install
    fs::path fromReg = ReadRegistryString(HKEY_LOCAL_MACHINE,
                                          L"SOFTWARE\\EpicGames\\Unreal Engine\\" + wassoc,
                                          L"InstalledDirectory");
    if (IsValidEngineRoot(fromReg)) return fromReg;

    // 3. Source build — the association is a GUID registered under the user's Builds key
    fs::path fromBuilds = ReadRegistryString(HKEY_CURRENT_USER,
                                             L"SOFTWARE\\Epic Games\\Unreal Engine\\Builds",
                                             wassoc);
    if (IsValidEngineRoot(fromBuilds)) return fromBuilds;

    // 4. Default launcher location
    fs::path fallback = L"C:\\Program Files\\Epic Games\\UE_" + wassoc;
    if (IsValidEngineRoot(fallback)) return fallback;

    return {};
}

// Resolves the engine root, asking the user once if every automatic lookup fails.
// A path entered by the user is persisted so later runs find it automatically.
fs::path ResolveEngineRootInteractive(const std::string& assoc)
{
    fs::path root = ResolveEngineRoot(assoc);
    if (!root.empty()) return root;

    std::cout << COL_YELLOW << "  Unreal Engine " << assoc << " not found automatically.\n"
              << "  Enter the engine root - the folder containing Engine\\\n" << COL_RESET
              << COL_WHITE << "  Path: " << COL_RESET;

    std::string input;
    if (!std::getline(std::cin, input) || input.empty())
        return {};

    // Strip surrounding quotes a user may have pasted along with the path
    if (input.size() >= 2 && input.front() == '"' && input.back() == '"')
        input = input.substr(1, input.size() - 2);

    fs::path candidate(input);
    if (!IsValidEngineRoot(candidate))
    {
        std::cout << COL_RED << "  [!] Invalid path - Engine\\Build\\BatchFiles\\Build.bat not found.\n" << COL_RESET;
        return {};
    }

    PersistUserEnvVar(EngineEnvVarName(assoc), candidate.wstring());
    std::cout << COL_GREEN << "  Saved. Future builds will find it automatically.\n" << COL_RESET;
    return candidate;
}

// ----------------------------------------------------------------
// Build
// ----------------------------------------------------------------

// Runs a batch file through cmd.exe, capturing stdout+stderr line by line.
// Output goes to onLine instead of the console, so the caller renders its own progress.
// Returns the process exit code, or -1 if the process could not be started.
int RunBatchCaptured(const fs::path& batFile, const std::wstring& args, const fs::path& workingDir,
                     const std::function<void(const std::string&)>& onLine)
{
    // cmd /c "<bat>" <args> — the outer quotes keep cmd from mangling paths with spaces
    std::wstring cmdLine = L"cmd.exe /c \"\"" + batFile.wstring() + L"\"";
    if (!args.empty()) cmdLine += L" " + args;
    cmdLine += L"\"";

    SECURITY_ATTRIBUTES sa = {};
    sa.nLength        = sizeof(sa);
    sa.bInheritHandle = TRUE;

    HANDLE readEnd = nullptr, writeEnd = nullptr;
    if (!CreatePipe(&readEnd, &writeEnd, &sa, 0)) return -1;
    // Only the child may inherit the write end — our read end must stay private
    SetHandleInformation(readEnd, HANDLE_FLAG_INHERIT, 0);

    STARTUPINFOW si = {};
    si.cb         = sizeof(si);
    si.dwFlags    = STARTF_USESTDHANDLES;
    si.hStdOutput = writeEnd;
    si.hStdError  = writeEnd;
    si.hStdInput  = GetStdHandle(STD_INPUT_HANDLE);

    PROCESS_INFORMATION pi = {};
    std::vector<wchar_t> mutableCmd(cmdLine.begin(), cmdLine.end());
    mutableCmd.push_back(L'\0');

    std::wstring wd = workingDir.wstring();
    if (!CreateProcessW(nullptr, mutableCmd.data(), nullptr, nullptr, TRUE, CREATE_NO_WINDOW, nullptr,
                        wd.empty() ? nullptr : wd.c_str(), &si, &pi))
    {
        CloseHandle(readEnd);
        CloseHandle(writeEnd);
        return -1;
    }
    // The parent must drop its copy of the write end or ReadFile never sees EOF
    CloseHandle(writeEnd);

    std::string pending;
    char  buffer[4096];
    DWORD read = 0;
    while (ReadFile(readEnd, buffer, sizeof(buffer), &read, nullptr) && read > 0)
    {
        pending.append(buffer, read);
        size_t nl;
        while ((nl = pending.find('\n')) != std::string::npos)
        {
            std::string text = pending.substr(0, nl);
            if (!text.empty() && text.back() == '\r') text.pop_back();
            pending.erase(0, nl + 1);
            if (onLine) onLine(text);
        }
    }
    if (!pending.empty() && onLine) onLine(pending);

    WaitForSingleObject(pi.hProcess, INFINITE);
    DWORD exitCode = 0;
    GetExitCodeProcess(pi.hProcess, &exitCode);
    CloseHandle(pi.hThread);
    CloseHandle(pi.hProcess);
    CloseHandle(readEnd);
    return (int)exitCode;
}

// ----------------------------------------------------------------
// Build progress rendering
// ----------------------------------------------------------------

const int PROGRESS_BAR_WIDTH = 28;

// Wipes the in-place progress line so normal output can be printed over it
void ClearProgressLine()
{
    std::cout << "\r" << std::string(PROGRESS_BAR_WIDTH + 28, ' ') << "\r" << std::flush;
}

// Redraws the single-line progress bar in place (no newline)
void PrintProgress(const std::string& label, int percent)
{
    percent = std::clamp(percent, 0, 100);
    int filled = (PROGRESS_BAR_WIDTH * percent) / 100;

    std::string pct = std::to_string(percent) + "%";
    std::ostringstream bar;
    bar << "\r  " << label << " " << COL_CYAN << "[";
    for (int i = 0; i < PROGRESS_BAR_WIDTH; ++i) bar << (i < filled ? "#" : ".");
    bar << "]" << COL_RESET << " " << COL_WHITE
        << std::string(4 - pct.size(), ' ') << pct << COL_RESET;
    std::cout << bar.str() << std::flush;
}

// UBT prefixes every compile/link action with "[123/456]" — the only progress signal we need
bool ParseActionProgress(const std::string& line, int& percent)
{
    size_t start = line.find_first_not_of(" \t");
    if (start == std::string::npos || line[start] != '[') return false;

    size_t close = line.find(']', start);
    size_t slash = line.find('/', start);
    if (close == std::string::npos || slash == std::string::npos || slash > close) return false;

    int done = 0, total = 0;
    try
    {
        done  = std::stoi(line.substr(start + 1, slash - start - 1));
        total = std::stoi(line.substr(slash + 1, close - slash - 1));
    }
    catch (...) { return false; }

    if (total <= 0) return false;
    percent = (int)((done * 100LL) / total);
    return true;
}

// Compiler/linker/UBT failures we still surface even though normal output is hidden
bool IsDiagnosticLine(const std::string& line)
{
    return ContainsIgnoreCase(line, ": error")
        || ContainsIgnoreCase(line, ": fatal error")
        || ContainsIgnoreCase(line, "error LNK")
        || line.rfind("ERROR", 0) == 0;
}

// Prints the captured tail of a failed run — the fallback when no diagnostic line was recognised
void PrintOutputTail(const std::vector<std::string>& tail)
{
    if (tail.empty()) return;
    std::cout << COL_GREY << "  --- last output ---" << COL_RESET << "\n";
    for (const auto& t : tail)
        if (!t.empty()) std::cout << COL_GREY << "  " << t << COL_RESET << "\n";
}

// Builds the project's crash reporter if the project ships one (Tools\CrashReporter\Build.bat).
// Projects without one are unaffected — this is a no-op that reports success.
bool BuildCrashReporter(const fs::path& startPath)
{
    fs::path crashReporterDir = startPath / "Tools" / "CrashReporter";
    fs::path buildBat = crashReporterDir / "Build.bat";
    std::error_code ec;
    if (!fs::exists(buildBat, ec)) return true;

    // Short step with no action counter — show an indeterminate bar and keep the output hidden
    PrintProgress("CrashReporter", 0);

    std::vector<std::string> tail;
    int code = RunBatchCaptured(buildBat, L"/nopause", crashReporterDir,
        [&](const std::string& text)
        {
            tail.push_back(text);
            if (tail.size() > 25) tail.erase(tail.begin());
        });

    ClearProgressLine();
    if (code != 0)
    {
        std::cout << COL_RED << "  [!] CrashReporter build failed (exit code " << code << ")." << COL_RESET << "\n";
        PrintOutputTail(tail);
        return false;
    }
    std::cout << COL_GREEN << "  CrashReporter ready." << COL_RESET << "\n";
    return true;
}

// Builds <ProjectName>Editor Win64 Development through the engine's UnrealBuildTool.
bool BuildProject(const fs::path& startPath)
{
    fs::path uproject = FindUprojectFile(startPath);
    if (uproject.empty())
    {
        std::cout << COL_RED << "  [!] No .uproject found in " << startPath.string() << COL_RESET << "\n";
        return false;
    }

    std::string assoc = ReadEngineAssociation(uproject);
    if (assoc.empty())
    {
        std::cout << COL_RED << "  [!] Could not read EngineAssociation from "
                  << uproject.filename().string() << COL_RESET << "\n";
        return false;
    }

    fs::path engineRoot = ResolveEngineRootInteractive(assoc);
    if (engineRoot.empty())
    {
        std::cout << COL_RED << "  [!] Engine root not resolved - build skipped." << COL_RESET << "\n";
        return false;
    }
    std::cout << COL_GREY << "  Engine: " << engineRoot.string() << COL_RESET << "\n";

    if (!BuildCrashReporter(startPath)) return false;

    std::string target = uproject.stem().string() + "Editor";
    std::wstring wtarget(target.begin(), target.end()); // safe: target names are ASCII

    std::cout << COL_CYAN << "  Building " << target << " (Win64 Development)" << COL_RESET << "\n";
    std::wstring args = wtarget + L" Win64 Development \"" + uproject.wstring() +
                        L"\" -WaitMutex -NoUBTMakefiles";

    const std::string label = "Compiling";
    std::vector<std::string> tail;          // kept only to explain a failure
    int  lastPercent        = 0;
    bool printedDiagnostic  = false;

    PrintProgress(label, 0);
    int code = RunBatchCaptured(engineRoot / ENGINE_BUILD_BAT, args, startPath,
        [&](const std::string& text)
        {
            tail.push_back(text);
            if (tail.size() > 40) tail.erase(tail.begin());

            int percent = 0;
            if (ParseActionProgress(text, percent))
            {
                if (percent != lastPercent) { lastPercent = percent; PrintProgress(label, percent); }
                return;
            }
            if (IsDiagnosticLine(text))
            {
                ClearProgressLine();
                std::cout << COL_RED << "  " << text << COL_RESET << "\n";
                printedDiagnostic = true;
                PrintProgress(label, lastPercent);
            }
        });

    ClearProgressLine();
    if (code != 0)
    {
        std::cout << COL_RED << "  [!] Build failed (exit code " << code << ")." << COL_RESET << "\n";
        if (!printedDiagnostic) PrintOutputTail(tail);
        return false;
    }
    PrintProgress(label, 100);
    std::cout << "\n" << COL_GREEN << "  Build succeeded." << COL_RESET << "\n";
    return true;
}

// ----------------------------------------------------------------
// UI
// ----------------------------------------------------------------

void PrintMenu(const std::vector<GroupInfo>& groups, const fs::path& startPath)
{
    system("cls");

    std::cout << COL_CYAN << COL_BOLD
              << "=====================================================\n"
              << "           UNREAL PROJECT CLEANER (C++)\n"
              << "=====================================================\n"
              << COL_RESET;
    std::cout << COL_WHITE << "Project: " << COL_RESET << startPath.string() << "\n\n";

    if (groups.empty())
    {
        std::cout << COL_GREY << "  No Binaries or Intermediate folders found.\n\n" << COL_RESET;
    }
    else
    {
        std::cout << COL_WHITE << COL_BOLD << "Folders:\n" << COL_RESET;

        // Calculate alignment widths
        size_t idxWidth  = std::to_string(groups.size()).size();
        size_t nameWidth = 0;
        size_t binNumWidth = 0;
        size_t midNumWidth = 0;
        for (auto& g : groups)
        {
            nameWidth  = std::max(nameWidth,  g.name.size());
            binNumWidth = std::max(binNumWidth, std::to_string(g.binariesCount).size());
            midNumWidth = std::max(midNumWidth, std::to_string(g.intermediateCount).size());
        }

        for (size_t i = 0; i < groups.size(); ++i)
        {
            const auto& g = groups[i];

            std::string idxStr = std::to_string(i + 1);
            std::string namePad(nameWidth - g.name.size(), ' ');
            std::string idxPad(idxWidth - idxStr.size(), ' ');

            // Right-align counts to their column widths
            auto padNum = [](int n, size_t w) {
                std::string s = std::to_string(n);
                return std::string(w - s.size(), ' ') + s;
            };

            std::string binStr = !g.binariesPath.empty()
                ? "[Binaries: "     + padNum(g.binariesCount,     binNumWidth) + "]"
                : std::string(12 + binNumWidth + 1, ' '); // blank same width as "[Binaries: NNN]"

            std::string midStr = !g.intermediatePath.empty()
                ? "[Intermediate: " + padNum(g.intermediateCount, midNumWidth) + "]"
                : "";

            std::string countStr = binStr + (midStr.empty() ? "" : " " + midStr);

            if (g.totalCount() == 0)
            {
                // Always green + CLEAN, never togglable
                std::cout << COL_GREEN
                          << "  [\xE2\x9C\x93] " << idxPad << idxStr << ". " << g.name << namePad << "  [CLEAN]"
                          << COL_RESET << "\n";
            }
            else if (g.selected)
            {
                std::cout << COL_RED
                          << "  [X] " << idxPad << idxStr << ". " << g.name << namePad << "  " << countStr
                          << COL_RESET << "\n";
            }
            else
            {
                std::cout << COL_GREY
                          << "  [ ] " << idxPad << idxStr << ". " << g.name << namePad << "  " << countStr
                          << COL_RESET << "\n";
            }
        }
        std::cout << "\n";
    }

    std::cout << COL_WHITE << COL_BOLD << "Commands:\n" << COL_RESET;
    std::cout << COL_YELLOW << "  a" << COL_RESET << "  - Select all\n";
    std::cout << COL_YELLOW << "  n" << COL_RESET << "  - Deselect all\n";
    std::cout << COL_YELLOW << "  c" << COL_RESET << "  - Clean selected\n";
    std::cout << COL_YELLOW << "  b" << COL_RESET << "  - Clean + Generate + Build + Open project (Clean Build)\n";
    std::cout << COL_YELLOW << "  g" << COL_RESET << "  - Generate project files\n";
    std::cout << COL_YELLOW << "  u" << COL_RESET << "  - Build editor (UnrealBuildTool)\n";
    std::cout << COL_YELLOW << "  r" << COL_RESET << "  - Refresh\n";
    std::cout << COL_YELLOW << "  q" << COL_RESET << "  - Quit\n";
    std::cout << "\n";
    std::cout << COL_GREY << "  Type a number to toggle (space-separated for multiple)\n" << COL_RESET;
    std::cout << "\n" << COL_WHITE << "Input: " << COL_RESET;
}

// ----------------------------------------------------------------
// Main loop
// ----------------------------------------------------------------

int main()
{
    EnableAnsiColors();
    SetConsoleOutputCP(CP_UTF8);
    SetConsoleCP(CP_UTF8);

    fs::path startPath = GetExeDir();

    std::cout << COL_YELLOW << "Scanning, please wait...\n" << COL_RESET;
    auto groups = FindTargetFolders(startPath);

    std::string line;
    while (true)
    {
        PrintMenu(groups, startPath);
        std::getline(std::cin, line);

        if (line == "q" || line == "Q") break;

        if (line == "a" || line == "A") { for (auto& g : groups) if (g.totalCount() > 0) g.selected = true;  continue; }
        if (line == "n" || line == "N") { for (auto& g : groups) g.selected = false; continue; }
        if (line == "r" || line == "R") { groups = FindTargetFolders(startPath); continue; }

        if (line == "c" || line == "C")
        {
            try { CleanSelected(groups, startPath); } catch (...) {}
            try { groups = FindTargetFolders(startPath); } catch (...) {}
            continue;
        }

        if (line == "g" || line == "G")
        {
            RunGenerateProjectFiles(startPath);
            continue;
        }

        if (line == "u" || line == "U")
        {
            std::cout << "\n";
            try { BuildProject(startPath); } catch (...) {}
            std::cout << COL_GREY << "\n  Press Enter to continue..." << COL_RESET;
            std::getline(std::cin, line);
            try { groups = FindTargetFolders(startPath); } catch (...) {}
            continue;
        }

        if (line == "b" || line == "B")
        {
            try { CleanSelected(groups, startPath); } catch (...) {}
            RunGenerateProjectFiles(startPath);

            // Don't open the editor on a failed build — it would load stale or missing binaries
            bool built = false;
            try { built = BuildProject(startPath); } catch (...) {}
            if (built)
            {
                fs::path uproject = FindUprojectFile(startPath);
                if (!uproject.empty())
                {
                    std::cout << COL_CYAN << "  Opening project: " << uproject.filename().string() << COL_RESET << "\n";
                    OpenUproject(uproject);
                }
            }
            else
            {
                std::cout << COL_GREY << "\n  Press Enter to continue..." << COL_RESET;
                std::getline(std::cin, line);
            }
            try { groups = FindTargetFolders(startPath); } catch (...) {}
            continue;
        }

        // Numbers - toggle selection
        std::istringstream iss(line);
        std::string token;
        while (iss >> token)
        {
            try
            {
                int idx = std::stoi(token) - 1;
                if (idx >= 0 && idx < (int)groups.size() && groups[idx].totalCount() > 0)
                    groups[idx].selected = !groups[idx].selected;
            }
            catch (...) {}
        }
    }

    return 0;
}
